spring: 
  application: 
    name: sistema-rh
  datasource:
    url: jdbc:postgresql://localhost:5432/rh
    password: admin
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa: 
    hibernate: 
      ddl-auto: update 