insert into Departamento (nome) values ('Accounting');
insert into Departamento (nome) values ('Marketing');
insert into Departamento (nome) values ('Legal');
insert into Departamento (nome) values ('Support');
insert into Departamento (nome) values ('Marketing');
insert into Departamento (nome) values ('Services');
insert into Departamento (nome) values ('Engineering');
insert into Departamento (nome) values ('Services');
insert into Departamento (nome) values ('Product Management');
insert into Departamento (nome) values ('Marketing');
insert into Departamento (nome) values ('Legal');
insert into Departamento (nome) values ('Business Development');
insert into Departamento (nome) values ('Product Management');
insert into Departamento (nome) values ('Research and Development');
insert into Departamento (nome) values ('Services');
